# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"
ruby '2.5.0'

gem 'shaf'
gem 'sinatra', require: 'sinatra/base'
gem 'rake'
gem 'thin'
gem 'sequel'
gem 'sinatra-sequel'
gem 'bcrypt'
gem 'hal_presenter'
gem 'redcarpet'

group :production, :development do
  gem 'pg'
end

group :development, :test do
  gem 'sqlite3'
end

group :test do
  gem 'sqlite3'
  gem 'minitest'
  gem 'rack-test'
end

