# frozen_string_literal: true

$LOAD_PATH.unshift __dir__ unless $LOAD_PATH.include? __dir__

require 'shaf/rake'
require 'shaf/settings'

namespace :test do
  Shaf::TestTask.new(:integration) do |t|
    t.pattern = "spec/integration/**/*_spec.rb"
  end

  Shaf::TestTask.new(:models) do |t|
    t.pattern = "spec/models/**/*_spec.rb"
  end

  Shaf::TestTask.new(:serializers) do |t|
    t.pattern = "spec/serializers/**/*_spec.rb"
  end

  Shaf::TestTask.new(:lib) do |t|
    t.pattern = "spec/lib/**/*_spec.rb"
  end

  Shaf::TestTask.new(:all) do |t|
    t.pattern = [
      "spec/lib/**/*_spec.rb",
      "spec/models/**/*_spec.rb",
      "spec/serializers/**/*_spec.rb",
      "spec/integration/**/*_spec.rb"
    ]
  end
end
